### PR TITLE
First release

### PR DESCRIPTION
**Pull request by lilitkarapetyan**

### CODE REVIEW

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan  - could you update the README to include the steps to run this, both in `serge` and `3rd-party`.

Oh, and the steps to test it.  I was unable to provide a valid connection string.

**Comment by lilitkarapetyan** [comment]
Note: please note taht to test the 3rd-party project, the serge project must be enabled on localhost using port 8080.

**Comment by lilitkarapetyan** [comment]
Note: The `Pull Request ` is currently in the development phase, and I haven't completed it yet

**Comment by lilitkarapetyan** [comment]
> Thanks @lilitkarapetyan - could you update the README to include the steps to run this, both in `serge` and `3rd-party`.
> 
> Oh, and the steps to test it. I was unable to provide a valid connection string.



> Thanks @lilitkarapetyan - could you update the README to include the steps to run this, both in `serge` and `3rd-party`.
> 
> Oh, and the steps to test it. I was unable to provide a valid connection string.

I have updated the README to include detailed instructions on how to run this.

**Comment by IanMayo** [comment]
Sure.  I was unable to provide a valid connection URL.  Could you provide an example of what a valid connection URL looks like.  It could go on the web-page.

Aah, also. There some bits committed in this branch that shouldn't be there.  I guess they are PyCharm bits, and the pycache.

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan 

> I was unable to provide a valid connection URL. Could you provide an example of what a valid connection URL looks like. It could go on the web-page.

Could you post in here a valid connection URL please?

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan
> 
> > I was unable to provide a valid connection URL. Could you provide an example of what a valid connection URL looks like. It could go on the web-page.
> 
> Could you post in here a valid connection URL please?

Start the Python server,  and then navigate to the specified URL http://localhost:5000/?wargame=wargame-l6nngxlk&access=umpire&host=https://serge-1720-move-back-to-wniicr.herokuapp.com. Once on the web page, locate and click the `connect ` button

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan ,
I've just had a play.  I was able to log into the wargame, but not to send a message.

I saw this error in the Serge terminal view:
image

From the flask app, it also indicated that the message could not be sent:
image

Aah, there's one other issue. I'd like to demonstrate listening for actual new messages, not new additions to the activity log.   This is because scientists may wish to listen for "new turn" or "new orders", do some processing in another application, and send results back into Serge.

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan , I've just had a play. I was able to log into the wargame, but not to send a message.
> 
> I saw this error in the Serge terminal view: image
> 
> From the flask app, it also indicated that the message could not be sent: image
> 
> Aah, there's one other issue. I'd like to demonstrate listening for actual new messages, not new additions to the activity log. This is because scientists may wish to listen for "new turn" or "new orders", do some processing in another application, and send results back into Serge.

Shouln't we send the new message as JSON ?

**Comment by IanMayo** [comment]
> Shouldn't we send the new message as JSON ?

In the description I gave, I was just imagining how they could integrate with Serge.

I am happy with the tasks that your app support. Well, plus the fixes described above.

**Comment by IanMayo** [comment]
Aah, I do have another observation.

The python/flask is currently quite _thin_, and the javascript is quite _fat_.

Are you able to take any steps to move JS functionality to Python?

**Comment by lilitkarapetyan** [comment]
> Aah, I do have another observation.
> 
> The python/flask is currently quite _thin_, and the javascript is quite _fat_.
> 
> Are you able to take any steps to move JS functionality to Python?

I will look into it.

**Comment by IanMayo** [comment]
Thanks for the update Lilit.  Please note: I'm still unable to submit messages to the game:
image

**Review by IanMayo — APPROVED** [review]
tested and working

**Pull request merged**
